# Generated by Django 3.2.6 on 2021-08-11 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
