# Generated by Django 3.2.5 on 2021-08-05 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_userfollowing_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='following_user_id',
            new_name='follower',
        ),
    ]
