# Generated by Django 3.2.5 on 2021-08-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_portfolio_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
