# Generated by Django 3.2.5 on 2021-08-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_items', '0004_delete_portfolio'),
        ('accounts', '0014_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='items_in_portfolio',
            field=models.ManyToManyField(to='art_items.ArtItem'),
        ),
    ]
