# Generated by Django 3.2.5 on 2021-08-05 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art_items', '0004_delete_portfolio'),
        ('accounts', '0017_auto_20210805_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='items_in_portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='art_items.artitem'),
        ),
    ]
