# Generated by Django 3.2.5 on 2021-08-05 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art_items', '0004_delete_portfolio'),
        ('accounts', '0019_alter_profile_items_in_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='items_in_portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='art_items.artitem'),
        ),
    ]
