# Generated by Django 3.2.5 on 2021-08-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='items_in_portfolio',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
