# Generated by Django 3.2.5 on 2021-08-06 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art_items', '0005_portfolio'),
        ('accounts', '0022_auto_20210806_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='items_in_portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='art_items.artitem'),
        ),
    ]
