# Generated by Django 3.2.5 on 2021-08-06 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_profile_items_in_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='items_in_portfolio',
        ),
    ]
