# Generated by Django 3.2.5 on 2021-08-08 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20210808_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user_to_follow',
            new_name='profile_to_follow',
        ),
    ]
