# Generated by Django 3.2.5 on 2021-08-08 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20210808_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='profile_to_follow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_to_follow', to='accounts.profile'),
        ),
    ]
