# Generated by Django 3.2.5 on 2021-08-09 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20210809_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='profile_to_follow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
