# Generated by Django 3.2.5 on 2021-07-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art_items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='art_item',
            new_name='item',
        ),
    ]
