# Generated by Django 3.2.5 on 2021-08-05 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_profile_age'),
        ('art_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.artifyuser')),
                ('uploaded_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art_items.artitem')),
            ],
        ),
    ]
