# Generated by Django 3.2.6 on 2021-08-12 21:31

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_items', '0002_auto_20210811_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artitem',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(50)]),
        ),
    ]
