# Generated by Django 3.2.5 on 2021-07-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art_items', '0002_auto_20210726_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
