# Generated by Django 3.2.5 on 2021-08-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art_items', '0003_alter_portfolio_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
