# Generated by Django 3.2.5 on 2021-08-06 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210806_1010'),
        ('art_items', '0004_delete_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.profile')),
                ('items_in_portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art_items.artitem')),
            ],
        ),
    ]
