# Generated by Django 3.2.5 on 2021-08-06 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art_items', '0006_alter_portfolio_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='items_in_portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='art_items.artitem'),
        ),
    ]
