# Generated by Django 3.2.5 on 2021-08-06 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_profile_items_in_portfolio'),
        ('art_items', '0007_alter_portfolio_items_in_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.profile'),
        ),
    ]
