# Generated by Django 3.2.5 on 2021-08-06 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art_items', '0010_alter_portfolio_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='items_in_portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art_items.artitem'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
