# Generated by Django 3.2.5 on 2021-08-06 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art_items', '0011_auto_20210806_1407'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
