# Generated by Django 3.2.5 on 2021-08-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_items', '0012_delete_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artitem',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
