# Generated by Django 3.2.5 on 2021-08-09 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_items', '0015_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artitem',
            name='name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
