# Generated by Django 3.2.5 on 2021-08-09 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_items', '0016_alter_artitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
