# Generated by Django 3.2.5 on 2021-08-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_items', '0018_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collections', models.ManyToManyField(blank=True, null=True, to='art_items.Collection')),
            ],
        ),
    ]
