# Generated by Django 3.2.5 on 2021-08-09 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20210808_1817'),
        ('art_items', '0019_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='followers',
        ),
        migrations.AddField(
            model_name='collection',
            name='content',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='art_items.artitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='accounts.profile'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
