# Generated by Django 3.2.5 on 2021-08-09 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20210809_2141'),
        ('art_items', '0020_auto_20210809_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='accounts.profile'),
        ),
    ]
